### ISSUE TITLE
Wrong Total liquidity in token page

### ISSUE THREAD

**Issue by thanhnguyennguyen** [pancakeswap/pancake-info#1]
As you can see in the following screenshot, liquidity of CAKE-WBNB pair only is > 9 million
![image](https://user-images.githubusercontent.com/17243442/95659642-929b3f80-0b4c-11eb-8111-181a5b92261a.png)

But the info page display, TotalLiquidity: 4 million

Same issue with uniswap.info https://github.com/Uniswap/uniswap-info/issues/286

**Comment by ChefKai** [comment]
This is a pair liquidity, so half liquidity belong to the first token, other half belong the the second one.

In this case, liquidity is $9M:
- $4.5M belong to CAKE
- $4.5M belong to WBNB (or BNB)

Hope that solves your question.
